name: Conventional Commits

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Validate current commit (last commit)
        if: github.event_name == 'push'
        run: bunx commitlint --last --verbose

      - name: Validate PR commits
        if: github.event_name == 'pull_request'
        run: bunx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Comment on PR with commit guidelines
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const message = `## ❌ Conventional Commits Check Failed
            
            Your commit messages don't follow the [Conventional Commits](https://www.conventionalcommits.org/) specification.
            
            ### Required Format:
            \`\`\`
            <type>[optional scope]: <description>
            
            [optional body]
            
            [optional footer(s)]
            \`\`\`
            
            ### Examples:
            - \`feat: add new test utility function\`
            - \`fix(hooks): resolve mock cleanup issue\`
            - \`docs: update installation instructions\`
            - \`test: add coverage for edge cases\`
            
            ### Valid Types:
            - **feat**: New feature
            - **fix**: Bug fix
            - **docs**: Documentation changes
            - **style**: Code style changes (formatting, etc.)
            - **refactor**: Code refactoring
            - **perf**: Performance improvements
            - **test**: Adding or updating tests
            - **build**: Build system changes
            - **ci**: CI/CD changes
            - **chore**: Maintenance tasks
            - **revert**: Revert previous commit
            
            Please update your commit messages and force push to resolve this issue.
            
            ### Quick Fix:
            You can use \`bun run commit\` to create conventional commits interactively.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });

      - name: Comment on successful validation
        if: success() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ All commit messages follow the Conventional Commits specification!'
            }); 
